# Generated by Django 5.2.4 on 2025-11-12 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herosection',
            name='tagline',
            field=models.TextField(),
        ),
    ]
