# Generated by Django 5.2.4 on 2025-11-12 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_herosection_tagline'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Meet Chovatiya', max_length=100)),
                ('profile_image', models.ImageField(upload_to='profile_images/')),
                ('education', models.CharField(default='Atmiya University, 2023–2026', max_length=255)),
                ('about_text', models.TextField()),
            ],
        ),
    ]
