# Generated by Django 5.2.4 on 2025-11-12 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('icon', models.ImageField(upload_to='skills/')),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='home.about')),
            ],
        ),
    ]
