# Generated by Django 5.2.4 on 2025-11-13 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=100)),
                ('rating', models.IntegerField(choices=[(1, '1 out of 5'), (2, '2 out of 5'), (3, '3 out of 5'), (4, '4 out of 5'), (5, '5 out of 5')])),
                ('feedback', models.TextField()),
            ],
        ),
    ]
