# Generated by Django 5.2.4 on 2025-11-13 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_testimonial_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='herosection',
            name='available_for_work',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='github',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='location',
            field=models.CharField(default='Rajkot', max_length=100),
        ),
    ]
