# Generated by Django 5.2.4 on 2025-11-13 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_herosection_available_for_work_herosection_github_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='herosection',
            name='github',
        ),
        migrations.RemoveField(
            model_name='herosection',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='herosection',
            name='linkedin',
        ),
        migrations.AddField(
            model_name='herosection',
            name='github_icon',
            field=models.ImageField(blank=True, null=True, upload_to='social_icons/'),
        ),
        migrations.AddField(
            model_name='herosection',
            name='instagram_icon',
            field=models.ImageField(blank=True, null=True, upload_to='social_icons/'),
        ),
        migrations.AddField(
            model_name='herosection',
            name='linkedin_icon',
            field=models.ImageField(blank=True, null=True, upload_to='social_icons/'),
        ),
    ]
