# Generated by Django 5.2.4 on 2025-11-13 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_remove_herosection_github_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='herosection',
            name='github_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='instagram_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
