# Generated by Django 5.2.4 on 2025-11-13 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_herosection_github_url_herosection_instagram_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='herosection',
            name='name_color',
            field=models.CharField(default='#be123c', help_text='Enter HEX color for your name, e.g. #be123c', max_length=7),
        ),
    ]
