# Generated by Django 5.2.4 on 2025-11-13 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_herosection_name_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='herosection',
            name='name_color',
        ),
    ]
