# Generated by Django 5.2.4 on 2025-11-13 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_remove_herosection_name_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='herosection',
            name='name_color',
            field=models.CharField(default='#be123c', help_text='Enter HEX color for your name, e.g. #be123c', max_length=7),
        ),
    ]
